substitutions:
  _REGION: asia-southeast1
  _CLUSTER_NAME: helm-cluster
  _HELM_RELEASE_NAME: myapp-release
  _NAMESPACE: default

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp:$SHORT_SHA'
      - '.'
    id: 'build-image'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp:$SHORT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Update values.yaml dynamically
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        echo "Updating values.yaml with PROJECT_ID: thematic-land-477215-a5"
        sed -i "s/PROJECT_ID/thematic-land-477215-a5/g" helm/myapp/values.yaml
        echo "Updated values.yaml:"
        cat helm/myapp/values.yaml
    id: 'update-values'

  # Step 4: Deploy Helm chart via Jumpbox VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Copying Helm chart to Jumpbox VM..."
        gcloud compute scp --recurse helm/myapp vij1542044@jumpbox-cluster:/tmp/helm-myapp \
          --zone=asia-southeast1-c \
          --project=thematic-land-477215-a5 \
          --quiet \
          --scp-flag="-o StrictHostKeyChecking=no" \
          --scp-flag="-o UserKnownHostsFile=/dev/null"

        echo "Deploying Helm chart via Jumpbox VM..."
        gcloud compute ssh vij1542044@jumpbox-cluster \
          --zone=asia-southeast1-c \
          --project=thematic-land-477215-a5 \
          --quiet \
          --ssh-flag="-o StrictHostKeyChecking=no" \
          --ssh-flag="-o UserKnownHostsFile=/dev/null" \
          --command "
            set -e
            sudo bash -c '
              echo Installing Helm...
              curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

              echo Preparing Helm directory...
              mkdir -p /root/helm/myapp
              cp -r /tmp/helm-myapp/* /root/helm/myapp/
              chown -R root:root /root/helm/myapp

              echo Checking chart structure:
              ls -R /root/helm/myapp

              echo Helm version:
              helm version

              echo Deploying Helm chart...
              cd /root/helm/myapp
              helm upgrade ${_HELM_RELEASE_NAME} . \
                --install \
                --create-namespace \
                --namespace ${_NAMESPACE} \
                --wait \
                --timeout 10m \
                --set image.repository=asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp \
                --set image.tag=$SHORT_SHA \
                --set env.APP_VERSION=v1.0.0-$SHORT_SHA \
                --kubeconfig /root/.kube/config \
                --debug

              echo Deployment complete!
            '
          "
    id: 'helm-deploy'
    waitFor: ['push-image', 'update-values']

  # Step 5: Verify deployment via Jumpbox VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying deployment via Jumpbox VM..."
        gcloud compute ssh vij1542044@jumpbox-cluster \
          --zone=asia-southeast1-c \
          --project=thematic-land-477215-a5 \
          --quiet \
          --ssh-flag="-o StrictHostKeyChecking=no" \
          --ssh-flag="-o UserKnownHostsFile=/dev/null" \
          --command "
            sudo bash -c '
              echo \"=== Verifying Deployment ===\"
              kubectl get all -n ${_NAMESPACE} -l app=myapp --kubeconfig /root/.kube/config
              
              echo \"\"
              echo \"=== Service Details ===\"
              kubectl get svc myapp-service -n ${_NAMESPACE} -o wide --kubeconfig /root/.kube/config
              
              echo \"\"
              echo \"=== Pod Status ===\"
              kubectl get pods -n ${_NAMESPACE} -l app=myapp --kubeconfig /root/.kube/config
              
              echo \"\"
              echo \"=== LoadBalancer IP (if available) ===\"
              kubectl get svc myapp-service -n ${_NAMESPACE} -o jsonpath=\"{.status.loadBalancer.ingress[0].ip}\" --kubeconfig /root/.kube/config || echo \"LoadBalancer IP not yet assigned\"
            '
          "
    id: 'verify-deployment'
    waitFor: ['helm-deploy']

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

timeout: '1800s'
