substitutions:
  _REGION: asia-southeast1
  _CLUSTER_NAME: helm-cluster
  _HELM_RELEASE_NAME: myapp-release
  _NAMESPACE: default

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp:$SHORT_SHA'
      - '.'
    id: 'build-image'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp:$SHORT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Update values.yaml dynamically
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        echo "Updating values.yaml with PROJECT_ID: thematic-land-477215-a5"
        sed -i "s/PROJECT_ID/thematic-land-477215-a5/g" helm/myapp/values.yaml
        echo "Updated values.yaml:"
        cat helm/myapp/values.yaml
    id: 'update-values'

  # Step 4: Get GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME}'
      - '--region'
      - '${_REGION}'
      - '--project'
      - 'thematic-land-477215-a5'
      - '--internal-ip'
    id: 'get-credentials'
    waitFor: ['push-image']

  # Step 5: Install Helm
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    id: 'install-helm'
    waitFor: ['get-credentials']

  # Step 6: Deploy with Helm - DIRECTLY from Worker Pool
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        /usr/local/bin/helm upgrade ${_HELM_RELEASE_NAME} helm/myapp \
          --install \
          --create-namespace \
          --namespace ${_NAMESPACE} \
          --wait \
          --timeout 10m \
          --set image.repository=asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp \
          --set image.tag=$SHORT_SHA \
          --set env.APP_VERSION=v1.0.0-$SHORT_SHA \
          --debug
    id: 'helm-deploy'
    waitFor: ['install-helm', 'update-values']

  # Step 7: Verify deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'get'
      - 'all'
      - '-n'
      - '${_NAMESPACE}'
      - '-l'
      - 'app=myapp'
    id: 'verify-deployment'
    waitFor: ['helm-deploy']

  # Step 8: Get LoadBalancer IP
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'get'
      - 'svc'
      - 'myapp-service'
      - '-n'
      - '${_NAMESPACE}'
      - '-o'
      - 'wide'
    id: 'get-service'
    waitFor: ['verify-deployment']

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/thematic-land-477215-a5/locations/asia-southeast1/workerPools/wp'
  dynamic_substitutions: true

timeout: '1800s'
