substitutions:
  _REGION: asia-southeast1
  _CLUSTER_NAME: helm-cluster
  _HELM_RELEASE_NAME: myapp-release
  _NAMESPACE: default

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp:$SHORT_SHA'
      - '.'
    id: 'build-image'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp:$SHORT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Update values.yaml dynamically
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        echo "Updating values.yaml with PROJECT_ID: thematic-land-477215-a5"
        sed -i "s/PROJECT_ID/thematic-land-477215-a5/g" helm/myapp/values.yaml
        echo "Updated values.yaml:"
        cat helm/myapp/values.yaml
    id: 'update-values'

  # Step 4: Get GKE credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME}'
      - '--region'
      - '${_REGION}'
      - '--project'
      - 'thematic-land-477215-a5'
    id: 'get-credentials'
    waitFor: ['push-image']

# Step 5: Deploy Helm chart via Jumpbox VM (Modified)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Copying Helm chart to Jumpbox VM..."
        # 💡 FIX 1: Copy the entire directory 'helm/myapp' to '/tmp/' on the VM.
        gcloud compute scp --recurse helm/myapp vij1542044@jumpbox-cluster:/tmp/ \
          --zone=asia-southeast1-c \
          --project=thematic-land-477215-a5 \
          --quiet \
          --ssh-flag="-o StrictHostKeyChecking=no" \
          --ssh-flag="-o UserKnownHostsFile=/dev/null"

        echo "Deploying Helm chart via Jumpbox VM..."
        gcloud compute ssh vij1542044@jumpbox-cluster \
          --zone=asia-southeast1-c \
          --project=thematic-land-477215-a5 \
          --quiet \
          --ssh-flag="-o StrictHostKeyChecking=no" \
          --ssh-flag="-o UserKnownHostsFile=/dev/null" \
          --command "
            set -e
            sudo bash -c '
              echo Installing Helm...
              curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

              echo Preparing Helm directory...
              # 💡 REMOVE unnecessary copy, we can work directly in the copied chart directory
              CHART_DIR=/tmp/myapp # 💡 NEW: Chart is now copied to /tmp/myapp/

              echo Checking chart structure:
              ls -R \${CHART_DIR} # 💡 Use the correct path

              echo Helm version:
              helm version

              echo Deploying Helm chart...
              cd \${CHART_DIR} # 💡 CD into the correct chart directory
              helm upgrade ${_HELM_RELEASE_NAME} . \
                --install \
                --create-namespace \
                --namespace ${_NAMESPACE} \
                --wait \
                --timeout 10m \
                --set image.repository=asia-southeast1-docker.pkg.dev/thematic-land-477215-a5/helm-demo-repo/myapp \
                --set image.tag=$SHORT_SHA \
                --set env.APP_VERSION=v1.0.0-$SHORT_SHA \
                --kubeconfig /root/.kube/config \
                --debug

              echo Deployment complete!
            '
          "
    id: 'helm-deploy'
    waitFor: ['get-credentials', 'update-values']

  # Step 6: Verify deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    args:
      - 'get'
      - 'all'
      - '-n'
      - '${_NAMESPACE}'
      - '-l'
      - 'app=myapp'
    id: 'verify-deployment'
    waitFor: ['helm-deploy']

  # Step 7: Get LoadBalancer IP
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    args:
      - 'get'
      - 'svc'
      - 'myapp-service'
      - '-n'
      - '${_NAMESPACE}'
      - '-o'
      - 'wide'
    id: 'get-service'
    waitFor: ['verify-deployment']

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

timeout: '1800s'
