substitutions:
  _REGION: asia-southeast1
  _CLUSTER_NAME: helm-cluster
  _HELM_RELEASE_NAME: myapp-release
  _NAMESPACE: default

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/helm-demo-repo/myapp:$SHORT_SHA'
      - '.'
    id: 'build-image'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/helm-demo-repo/myapp:$SHORT_SHA'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Update values.yaml
  - name: 'ubuntu'
    args:
      - 'bash'
      - '-c'
      - |
        echo "Updating values.yaml with PROJECT_ID: $PROJECT_ID"
        sed -i "s/PROJECT_ID/$PROJECT_ID/g" helm/myapp/values.yaml
        echo "Updated values.yaml:"
        cat helm/myapp/values.yaml
    id: 'update-values'

  # Step 4: Get cluster credentials (for regional cluster)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_CLUSTER_NAME}'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '$PROJECT_ID'
    id: 'get-credentials'
    waitFor: ['push-image']

  # Step 5: Deploy via Jumpbox VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing Helm and deploying via Jumpbox VM..."
        gcloud compute ssh root@jumpbox-cluster \
          --zone=asia-southeast1-c --quiet --command "
            set -e
            echo 'Installing Helm...'
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            echo 'Helm version:'
            helm version

            echo 'Deploying Helm chart...'
            cd /root
            helm upgrade ${_HELM_RELEASE_NAME} /root/helm/myapp \
              --install \
              --create-namespace \
              --namespace ${_NAMESPACE} \
              --wait \
              --timeout 10m \
              --set image.repository=${_REGION}-docker.pkg.dev/$PROJECT_ID/helm-demo-repo/myapp \
              --set image.tag=$SHORT_SHA \
              --set env.APP_VERSION=v1.0.0-$SHORT_SHA \
              --kubeconfig /root/.kube/config \
              --debug

            echo 'Deployment complete!'
          "
    id: 'helm-deploy'
    waitFor: ['get-credentials', 'update-values']

  # Step 6: Verify deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    args:
      - 'get'
      - 'all'
      - '-n'
      - '${_NAMESPACE}'
      - '-l'
      - 'app=myapp'
    id: 'verify-deployment'
    waitFor: ['helm-deploy']

  # Step 7: Get LoadBalancer IP
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    args:
      - 'get'
      - 'svc'
      - 'myapp-service'
      - '-n'
      - '${_NAMESPACE}'
      - '-o'
      - 'wide'
    id: 'get-service'
    waitFor: ['verify-deployment']

options:
  machineType: 'E2_HIGHCPU_4'
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

timeout: '1800s'
